-- MySQL Script generated by MySQL Workbench
-- jue 09 feb 2017 20:58:39 VET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`carreras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`carreras` ;

CREATE TABLE IF NOT EXISTS `mydb`.`carreras` (
  `car_id` INT NOT NULL AUTO_INCREMENT,
  `car_nb` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`car_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`generos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`generos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`generos` (
  `gen_id` INT NOT NULL AUTO_INCREMENT,
  `gen_nb` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`gen_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`operadoras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`operadoras` ;

CREATE TABLE IF NOT EXISTS `mydb`.`operadoras` (
  `ope_id` INT NOT NULL AUTO_INCREMENT,
  `ope_nb` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ope_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`deportes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`deportes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`deportes` (
  `dep_id` INT NOT NULL AUTO_INCREMENT,
  `dep_nb` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dep_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`semestres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`semestres` ;

CREATE TABLE IF NOT EXISTS `mydb`.`semestres` (
  `sem_id` INT NOT NULL AUTO_INCREMENT,
  `sem_nb` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sem_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`materias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`materias` (
  `mat_id` INT NOT NULL AUTO_INCREMENT,
  `mat_nb` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`mat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estados_civiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estados_civiles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estados_civiles` (
  `eci_id` INT NOT NULL AUTO_INCREMENT,
  `eci_nb` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`eci_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`redes_sociales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`redes_sociales` ;

CREATE TABLE IF NOT EXISTS `mydb`.`redes_sociales` (
  `rso_id` INT NOT NULL AUTO_INCREMENT,
  `rso_nb` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rso_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`personas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`personas` (
  `personas_id` INT NOT NULL AUTO_INCREMENT,
  `personas_ci` VARCHAR(45) NOT NULL,
  `personas_nombre` VARCHAR(45) NOT NULL,
  `personas_apellido` VARCHAR(45) NOT NULL,
  `generos_gen_id` INT NOT NULL,
  `estados_civiles_eci_id` INT NOT NULL,
  `carreras_car_id` INT NOT NULL,
  `semestres_sem_id` INT NOT NULL,
  `deportes_dep_id` INT NOT NULL,
  PRIMARY KEY (`personas_id`),
  INDEX `fk_personas_generos_idx` (`generos_gen_id` ASC),
  INDEX `fk_personas_estados_civiles1_idx` (`estados_civiles_eci_id` ASC),
  INDEX `fk_personas_carreras1_idx` (`carreras_car_id` ASC),
  INDEX `fk_personas_semestres1_idx` (`semestres_sem_id` ASC),
  INDEX `fk_personas_deportes1_idx` (`deportes_dep_id` ASC),
  CONSTRAINT `fk_personas_generos`
    FOREIGN KEY (`generos_gen_id`)
    REFERENCES `mydb`.`generos` (`gen_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personas_estados_civiles1`
    FOREIGN KEY (`estados_civiles_eci_id`)
    REFERENCES `mydb`.`estados_civiles` (`eci_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personas_carreras1`
    FOREIGN KEY (`carreras_car_id`)
    REFERENCES `mydb`.`carreras` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personas_semestres1`
    FOREIGN KEY (`semestres_sem_id`)
    REFERENCES `mydb`.`semestres` (`sem_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personas_deportes1`
    FOREIGN KEY (`deportes_dep_id`)
    REFERENCES `mydb`.`deportes` (`dep_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relacion_personas_telefonos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`relacion_personas_telefonos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`relacion_personas_telefonos` (
  `rpt_id` INT NOT NULL AUTO_INCREMENT,
  `rpt_nr_telefono` VARCHAR(45) NOT NULL,
  `operadoras_ope_id` INT NOT NULL,
  PRIMARY KEY (`rpt_id`),
  INDEX `fk_relacion_personas_telefonos_operadoras1_idx` (`operadoras_ope_id` ASC),
  CONSTRAINT `fk_relacion_personas_telefonos_operadoras1`
    FOREIGN KEY (`operadoras_ope_id`)
    REFERENCES `mydb`.`operadoras` (`ope_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personas_has_materias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`personas_has_materias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`personas_has_materias` (
  `personas_per_id` INT NOT NULL,
  `materias_mat_id` INT NOT NULL,
  PRIMARY KEY (`personas_per_id`, `materias_mat_id`),
  INDEX `fk_personas_has_materias_materias1_idx` (`materias_mat_id` ASC),
  INDEX `fk_personas_has_materias_personas1_idx` (`personas_per_id` ASC),
  CONSTRAINT `fk_personas_has_materias_personas1`
    FOREIGN KEY (`personas_per_id`)
    REFERENCES `mydb`.`personas` (`personas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personas_has_materias_materias1`
    FOREIGN KEY (`materias_mat_id`)
    REFERENCES `mydb`.`materias` (`mat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`redes_sociales_has_personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`redes_sociales_has_personas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`redes_sociales_has_personas` (
  `redes_sociales_rso_id` INT NOT NULL,
  `personas_per_id` INT NOT NULL,
  PRIMARY KEY (`redes_sociales_rso_id`, `personas_per_id`),
  INDEX `fk_redes_sociales_has_personas_personas1_idx` (`personas_per_id` ASC),
  INDEX `fk_redes_sociales_has_personas_redes_sociales1_idx` (`redes_sociales_rso_id` ASC),
  CONSTRAINT `fk_redes_sociales_has_personas_redes_sociales1`
    FOREIGN KEY (`redes_sociales_rso_id`)
    REFERENCES `mydb`.`redes_sociales` (`rso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_redes_sociales_has_personas_personas1`
    FOREIGN KEY (`personas_per_id`)
    REFERENCES `mydb`.`personas` (`personas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
