
		                    <?php if (isset($this->errorNum)) echo $this->errorNum?>
		                 
		                    <?php if (isset($this->message)) echo $this->message?>
		                 
		                  
		                  <?php if (!Session::get('authenticated')):?>
		                    <a class='btn btn-md btn-ablock' href='<?php echo BASE_URL . 'login/index'; ?>'>
		                     
		                      iniciar Sesión
		                    </a>
		                  <?php else:?>
		                 
		                    <a class='btn btn-md btn-ablock' href='javascript: history.go(-1)'>
		                     
		                      Regresar
		                    </a>
		                  <?php endif;?>
		                  
		                