
 			<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">
 					<div class= "panel-heading">
 						<h3 class= "panel-title"> NOMBRE DEL MODULO </h3>
 					</div>
 					
 					<div class="panel-body">

<form class="form-horizontal" role="form" action="<?php  echo BASE_URL;?>persons/insert"	method="post">

				<h1>BootsTrap</h1>
				<h1>LibrosWEb Boostrap El manual Oficial</h1>



				<table class="table table-bordered table-hover" hidden>
					<thead>
						<tr>
							<th>Cedula</th>
							<th>NOmbre</th>
							<th>NOmbre2</th>
							<th>Apellido2</th>
							<th>Apellido1</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<th>23926305</th>
							<th>Eduardo</th>
							<th>Jose</th>
							<th>Parra</th>
							<th>Rodriguez</th>
						</tr>
					</tbody>
				</table>

				<div class="form-group">
					<label class="col-sm-3"for="">Nombres</label>
					<div  class="col-sm-4 " >
						<input type="text" class="form-control" placeholder="Nombre1" title="ESTO PUEDE SER UNA AYUDA" required >
					</div>
					<div class="col-sm-4">
						<input class="form-control" type="text" placeholder="NOmbre2" title="ESTO PUEDE SER UNA AYUDA" required>
					</div>
				</div>
				<input type="submit" class="btn btn-primary btn-sm">




				<br>
				<br>
				<br>
				<br>
				<br>
				<div class="form-group">
					<label class="col-sm-3"for="">Tipo de Persona</label>
					<div  class="col-sm-4 " >
						<select class="form-control" name="tipo" id="tipo">
					<option value="1">Seleccione..</option>
					<option value="2">Pobresor</option>
					<option value="3">Alumno</option>
					


				</select>

					</div>
				</div>
				



				<div class="form-group" id="escondido" hidden>
					<label class="col-sm-3"for="">Usuario</label>
					<div  class="col-sm-4 " >
						<input type="text" class="form-control" placeholder="Usuario" title="ESTO PUEDE SER UNA AYUDA" required >
					</div>
					<div class="col-sm-4">
						<input class="form-control" type="text" placeholder="Clave" title="ESTO PUEDE SER UNA AYUDA" required>
					</div>
				</div>

				
</form>
 					</div>
 				</div>
 		</div>
 			<!-- no borrar -->
 			</div>
 			
 		</div>
 	</div>

 	
 	
 				
 					
 					
 					
 					