<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">
 					<div class= "panel-heading">
 						<h3 class= "panel-title"> MODULO PERSONAS </h3>
 					</div>
 					
 					<div class="panel-body">
 					<form class="form-horizontal" role="form" action=""	method="post">

 					
 					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
 		 tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
 		 ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
 		 velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in 
 		 culpa qui officia deserunt mollit anim id est laborum. 
 					<br><br>
 					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
 		 tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
 		 ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
 		 velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in 
 		 culpa qui officia deserunt mollit anim id est laborum.
 					
 					<br><br>
 					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
 		 tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
 		 ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
 		 velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in 
 		 culpa qui officia deserunt mollit anim id est laborum.
 		 			</form>
 					</div>
 				</div>
 		</div>
 			
 			</div>
 			
 		</div>
 	</div>