<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">
 					<div class= "panel-heading">
 						<h3 class= "panel-title"> Nueva Persona	</h3>
 					</div>
 					
 					<div class="panel-body">

 						<form id="persons_insert" class="form-horizontal"  action="<?php  echo BASE_URL;?>persons/insert" method="post">
	 						<div class="form-group">
	 							<label class="col-sm-4 control-label">Cedula</label>
		 						<div class="col-sm-4">
		 							<input type="text" class="form-control" name="cedula">
		 						</div>
	 						</div>

	 						<div class="form-group">
	 							<label class="col-sm-4 control-label">Nombre</label>
		 						<div class="col-sm-4">
		 							<input type="text" class="form-control" name="nombre">
		 						</div>
	 						</div>

	 						<div class="form-group">
	 							<label class="col-sm-4 control-label">Apellido</label>
		 						<div class="col-sm-4">
		 							<input type="text" class="form-control" name="apellido">
		 						</div>
	 						</div>

	 						<div class="form-group">
	 							<label class="col-sm-4 control-label">Sexo</label>
		 						<div class="col-sm-4">
		 							<input type="text" class="form-control" name="sexo">
		 						</div>
	 						</div>

	 						<div class="form-group">
	 							<label class="col-sm-4 control-label">Fecha de Nacimiento</label>
		 						<div class="col-sm-4">
		 							<input type="date" class="form-control" name="fecha_nacimiento">
		 						</div>
	 						</div>

	 						<div class="form-group">
	 							<label class="col-sm-4 control-label">Telefono</label>
		 						<div class="col-sm-4">
		 							<input type="text" class="form-control" name="telefono">
		 						</div>
	 						</div>
	 						
	 						<div class="form-group">
	 							<label class="col-sm-4 control-label">Correo</label>
		 						<div class="col-sm-4">
		 							<input type="text" class="form-control" name="correo">
		 						</div>
	 						</div>

							<div class="form-group">
								<div class="col-sm-offset-5 ">
	 								<input type="submit" class="btn btn-primary">
	 							</div>
							</div>
							
						</form>
						

 					</div>
 				</div>
 		</div>
 			<!-- no borrar -->
 			</div>
 			
 		</div>
 </div>

 	
 	
 				
 					
 					
 				




 	