<div  class= "col-xs-9 col-sm-9 col-md-9 col-lg-9">
 				<div class= "panel panel-primary">
 					<div class= "panel-heading">
 						<h3 class= "panel-title"> Nueva Persona	</h3>
 					</div>
 					
 					<div class="panel-body">

 						<form action="<?php  echo BASE_URL;?>persons/select" method="post">

	 						
								<select name="sexo" id="sexo">
									
								</select>
							

							
						</form>

 					</div>
 				</div>
 		</div>
 			<!-- no borrar -->
 			</div>
 			
 		</div>
 </div>

 	
 	
 				
 					
 					
 				




 	