<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
					<div class="list-group">
						<a  class="list-group-item active">Menu</a>
						
						<?php  if ($_view_params['sidebar_menu']):?>
						<?php for ($i = 0; $i < count($_view_params['sidebar_menu']); $i++):?>
<a href="<?php echo $_view_params['sidebar_menu'][$i]['link']; ?>"class="list-group-item"><?php echo $_view_params['sidebar_menu'][$i]['title'];?></a> 
						<?php endfor;?>
						<?php endif;?>
						
						
				</div>
				</div>
				
				
				